### ISSUE TITLE
recursos adicionales de la api de georef-ar

### ISSUE THREAD

**Issue by jgjuara** [PoliticaArgentina/geoAr#11]
funcion para el endpoint de localidades censales: https://github.com/jgjuara/georefar/blob/7ed28f775189746fddb660d5ac60c49e94567288/R/localidades_censales.R 

funcion para el endpoint de asentamientos:
https://github.com/jgjuara/georefar/blob/7ed28f775189746fddb660d5ac60c49e94567288/R/asentamientos.R

**Comment by pdelboca** [comment]
@jgjuara te interesa crear un PR para integrar estos metodos al paquete?

Saludos!

**Comment by TuQmano** [comment]
Incorporados en https://github.com/PoliticaArgentina/geoAr/pull/14
