### ISSUE TITLE
Soporte de Token para la API de georef-ar

### ISSUE THREAD

**Issue by pdelboca** [PoliticaArgentina/geoAr#12]
La API de `georef-ar` cuenta con la posibilidad de autenticarse con JWT pero la funcionalidad incorporada desde https://github.com/pdelboca/georefar no da soporte para este caso de uso.

## Detalles

Documentación de la API: https://datosgobar.github.io/georef-ar-api/jwt-token/

```python
>>> import requests
>>> headers = { 'Authorization': 'Bearer {}'.format(token) }
>>> resp = requests.get('https://apis.datos.gob.ar/georef/api/provincias', headers=headers)
>>> resp.json()
{
    'provincias': [
        { ... }
    ]
}
```

## Implementación
1. Crear un nuevo método GET interno (por ejemplo `_GET()`) en `/georefar.R` que agregue headers
2. Obtener el token the una variable de entorno
3. Reemplazar todas las llamadas a GET() por _GET()

#### Pseudo Codigo:

Funcion `_GET` (o nombre similar):
```r
_GET <- function(url, ...) {
  # Obtener el token de la variable de entorno
  token <- Sys.getenv("GEOREFAR_TOKEN")

  # Comprobar si el token está presente
  if (is.null(token) || token == "") {
    response <- GET(url, ...)
  } else {
   response <- GET(url, ...,add_headers(Authorization = paste("Bearer", token)))
}
  # Comprobar el código de estado de la respuesta
  if (status_code(response) == 200) {
    # La solicitud fue exitosa
    return(response)
  } else {
    # La solicitud falló
    stop("La solicitud GET falló. Código de estado: ", status_code(response))
  }
}
```
Uso de la funcion:
```r
  base_url_get_localidades_censales <- paste0(base_url, "localidades-censales")
  # res <- GET(base_url_get_localidades_censales, query = compact(args)) # actual
   res <- _GET(base_url_get_localidades_censales, query = compact(args)) # cambio requerido 
```
Referencias:
 - https://httr.r-lib.org/reference/add_headers.html
 - https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Sys.getenv

**Comment by jgjuara** [comment]
quizás está bien meter un param para que el usuario decida si usar el token o no, por si acaso el usuario tiene un token guardado pero quiere hacer alguna consulta  sin usarlo. otra cosa: el token se generaría aparte o habría que armar una función que le pases el secret y la key y te devuelva el token? qué les parece?

**Comment by TuQmano** [comment]
La lógica en este caso de uso (con _token_) entonces sería algo así? 

1. Si pongo param  `token = TRUE/FALSE`
1. Si es `TRUE`
a. Chequea con func interna si hay variable de entorno con token creada ?
*  Si ya se creó y está guardada en el `.Renviron` entonces hace consulta con la versión condicional con token (metodo `_GET` interno, propuesto por @pdelboca )
 * Si no se creo, abre el `.Renviron` (con un print en consola con instrucciones) para crearlas
2. Si es `FALSE` (por defecto?) genera consulta con método `GET `vigente

**Comment by pdelboca** [comment]
## TL/DR

Yo no agregaría más código para manejar este escenario. Si no quiero usar el token no lo seteo como variable de entorno y listo. (Pero me amoldo a lo que decida quien lo implementa.)

## Detalles

A este punto es cuestión de preferencias personales y casos de uso. Hay que pensar cómo queremos que se comporte el programa cuando el desarrollador no esté presente para manejar esta variable de entorno.

En cuanto a diseño:
 - Si la apikey es una propiedad del wrapper o del programa, entonces se maneja a nivel variable de entorno.
 - Si la apikey es una propiedad de la función, entonces no queda otra que parametrizarlo.
 - wrappers cuya función es automatizar procesos **O** el token no tiene límites estrictos: variable de entorno.
 - wrappers cuya función es explorativa **O** la APIKey tiene límites estrictos: parametro.

Tiene límites de uso el Token? O es un Free pass? Si no tiene límites de uso yo no lo agregaría porque es más código que mantener y me da fiaca :P

A nivel más serio, yo solo pondría el parámetro token si las ejecuciones automáticas de mi script/programa necesitan un control fino de qué funciones usan token y cuales no.

### A nivel Wrapper

Es la solución que propuse. La ventaja es que es menos código que mantener y el princpio es que cuando se hagan ejecuciones automáticas entonces todas las llamadas usarán el token.

Mientras desarrollo, si no quiero usar el token, directamente no lo seteo.

### A nivel funcion

Directamente ponemos un parámetro `token=....` en las llamadas de las funciones. No pongamos una variable booleana que sea proxy porque va a ensuciar un poco el código. Directamente usemos el token.

```r
token <- Sys.getenv("GEOREFAR_TOKEN")
localidades <- get_localidades(..., token=token)
```

```r
_GET <- function(url, token, ...) {
  # Comprobar si el token está presente
  if (is.null(token) || token == "") {
    response <- GET(url, ...)
  } else {
   response <- GET(url, ...,add_headers(Authorization = paste("Bearer", token)))
}
...
}
```

**Comment by pdelboca** [comment]
No tengo una opinion fuerte sobre la otra funcion para generar el token. 

Es un lindo agregado pero dado que el token se genera una sola vez y se guarda la agregaría sólo si alguien tiene tiempo y ganas de hacerla 👍🏼

**Comment by gonzaloazuaga2021** [comment]
Hola a todos, en relación a la pregunta de patricio: "Tiene límites de uso el Token? O es un Free pass?, la gente de datos abiertos me comentó (en su momento) que con el token se pueden hacer hasta 650.000 por día. A su vez, me dijieron que se pueden hacer las consultas por lotes (utilizando la función post) y que eso demanda menos consultas, en vez de utilizar la función get (entiendo que las funciones dentro del paquete emplean el get) ¿No sé si ven factible agregar en algún momento alguna función que haga llamados por lotes? Saludos!

**Comment by jgjuara** [comment]
retomando la respuesta de @pdelboca entonces propongo que las funciones de llamada georef usen este esquema de funciones auxiliares:

```r

check_internet <- function(){
  attempt::stop_if_not(.x = curl::has_internet(),
                       msg = "No se detecto acceso a internet. Por favor chequea tu conexion.")
}

check_status <- function(res){
  attempt::stop_if_not(.x = httr::status_code(res),
              .p = ~ .x == 200,
              msg = httr::message_for_status(res, "get data from API"))
}

base_url <- "http://apis.datos.gob.ar/georef/api/"


get_endpoint <- function(endpoint, ...) {

  # Obtener el token de la variable de entorno
  token <- Sys.getenv("GEOREFAR_TOKEN")

  url <- paste0(base_url, endpoint)

  # Comprobar si el token está presente
  if (is.null(token) | token == "") {
    response <- httr::GET(url, ...)
  } else {
    response <- httr::GET(url,
                          httr::add_headers(Authorization = paste("Bearer", token)),
                          ...)
  }

  check_status(response)

 jsonlite::fromJSON(httr::content(response, "text"))[[endpoint]] %>%
    purrr::modify_if(is.null, list) %>%
    jsonlite::flatten(recursive = T) %>%
    dplyr::as_tibble(.name_repair = function(x) {gsub(pattern = "\\$|\\.", replacement = "_", x = x)}) %>%
    suppressMessages()
}
```

Entonces por ejemplo para un endpoint dado quedaría:

```r

get_calles <- function(id = NULL, nombre = NULL, tipo = NULL, provincia = NULL, departamento = NULL, aplanar = TRUE, campos = NULL, max = NULL, exacto = NULL){

  args <- purrr::compact(list(id = id, nombre = nombre, tipo = tipo, provincia = provincia, departamento = departamento, aplanar = aplanar, campos = campos, max = max, exacto = exacto))

  endpoint <- "calles"

  check_internet()

  get_endpoint(endpoint = endpoint, ... = args)

}
```

**Comment by TuQmano** [comment]
A mi me gusta la lógica de como queda armada así. 
Ya lo testeaste @jgjuara ?

**Comment by jgjuara** [comment]
Sí para un endpoint voy a modificar todas funciones de get_ y pruebo todo, trato de mejorar el mensaje de error además cuando falla el get pero hay internet. Dps hago PR

**Comment by TuQmano** [comment]
Incorporado en https://github.com/PoliticaArgentina/geoAr/pull/14
