### ISSUE TITLE
Agregar funciones del wraper georefar a {geoAr}

### ISSUE THREAD

**Issue by TuQmano** [PoliticaArgentina/geoAr#8]
R wrapper for georef-ar API. https://georef-ar-api.readthedocs.io/es/latest/

por @pdelboca

**Comment by pdelboca** [comment]
Ya que estamos integrando. Sería bueno cambiar el mensaje de error de `check_status()`: https://github.com/PoliticaArgentina/geoAr/blob/9fbde65371fb4509bc57b23543ed07fce72b521b/R/georefar.R#L7-L12

Es de muy alto nivel y a veces los usarios no saben si es un error del paquete o del servicio. Sería bueno devolver a) el mensaje de error que venga en la response o b) si es un `500` que el error está en el servicio y no en el paquete.

**Comment by TuQmano** [comment]
Por ahora lo armé así. Dejando mensaje de la respuesta y "aclaracion" que no se pudo obtener datos de la API (como estaba) https://github.com/PoliticaArgentina/geoAr/commit/5ae01e6a8884b2a6d19c603fb343d5a8f31ac204

```
check_status <- function(res){
  attempt::stop_if_not(.x = httr::status_code(res),
              .p = ~ .x == 200,
              msg = httr::message_for_status(res, "get data from API"))
}
```

Si le tiro a esta URL (con un 404, por ejemplo), devuelve lo siguiente: 

```
 res <- httr::GET("http://httpbin.org/status/404")
> check_status(res)
Not Found (HTTP 404). Failed to get data from API.
```

Con un 500: 
```

> res <- httr::GET("http://httpbin.org/status/500")
> check_status(res)
Internal Server Error (HTTP 500). Failed to get data from API.
```

**Comment by TuQmano** [comment]
Las funciones y (una primera versión de mejora de) el mensaje de error ya fueron incoprporados en https://github.com/PoliticaArgentina/geoAr/commit/5ae01e6a8884b2a6d19c603fb343d5a8f31ac204
